export const homePage: string = "http://localhost:4003/"
export const homeBackgroundimg: string = "https://i.pinimg.com/564x/20/be/a7/20bea7a917a43b11f1f5f994e00b833e.jpg"
export const productCategory = ["phone", "laptop"]

export const backEndPage: string = import.meta.env.VITE_BACKEND_URL
export const categoryPath: string = "/category"
export const productPath: string = "/product"
export const quantityPath: string = `${productPath}/quantity`
export const searchPath: string = `${productPath}/searching`
export const findById: string = `${productPath}/product-id`
export const producerBasePath : string = "/producer"
export const mailServerBaseUrl: string = "http://localhost:8087/"
export const mailPath: string = "/mail/code"
export const loginPath: string = "/login"
export const registerPath: string = "/register"
export const refreshTokenPath: string = "/auth/refresh-token"
export const userPath: string = "/user"
export const authenticatePath : string = "/auth/authenticate"
export const userResponsePath : string= `${userPath}/user-id`
export const orderPath : string = "/order"
export const carouselPath : string = "/carousel"